# Dependabot will run on day 11 of each month at 02:21 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "21 2 11 * *"
    open-pull-requests-limit: 20
    assignees:
      - "Bannsaenger"
    versioning-strategy: "increase"
